[package]
name = "graphite-host"
version = "0.1.0"
edition = "2021"

[dependencies]

# todo: update tao and wry
wry = "0.24"
tao = "0.16"

serde = { version = "1.0", features = ["derive"] }

serde_json = "1.0"

anyhow = "1.0"
